### ISSUE TITLE
Creacion de "elSalvadorJS"

### ISSUE THREAD

**Issue by eafelix** [latamjs/comunidades#2]
Issue para dar ayuda a @ricardoerl y sus amigos en la primera comunidad JS de El Salvador. 
Aca puede darnos una mano @julianduque que tiene varios contactos de las comunidades en la region de Centro America.

**Comment by francisbrito** [comment]
:+1: 

Me interesa ayudar con el tema o la presentación. Como puedo apoyarles?

PD: Soy co-organizador de la comunidad de [JavaScript en República Dominicana](https://www.facebook.com/groups/JavaScriptDominicana).

**Comment by ricardoerl** [comment]
@francisbrito ¿que herramientas usan para organizar y convocar a las personas? Actualmente usamos un grupo de Facebook para comunicarnos a veces creo que no es muy eficiente.

**Comment by francisbrito** [comment]
@ricardoerl de hecho, tampoco me parece adecuado, sin embargo los miembros de la comunidad dominicana prefieren Facebook para manejar comunicación y eventos.

Quizás les interese usar [la plantilla de proyecto](https://github.com/JedWatson/sydjs-site) que hicieron los chicos de [SydneyJS](http://www.sydjs.com/). Tiene manejador de miembros y charlas.

**Comment by mgtitimoli** [comment]
@francisbrito @ricardoerl, les comparto una alternativa que puede llegar a andar: pueden utilizar el mismo slack de latamjs, y crear un canal para su region, por ej #republica-dominicana, y luego utilizar ti.to para los eventos,

**Comment by julianduque** [comment]
@ricardoerl en lo que pueda ayudar dejamelo saber!

**Comment by eafelix** [comment]
Yo analizaría cual es el canal mas utilizado en cada region, acá en Argentina se usa mucho meetup.com  y facebook muy poco para este tipo de eventos. 
Si conoces otras comunidades de otras tecnologias que tengan muchas concurrencias, podrías relevar que usan para su difusion y sus canales de comunicación, para poder implementarlo. 
De no existir, podrías elegir la que vos desees.

**Comment by nisnardi** [comment]
Nosotros en http://www.meetup.com/meetup-js usamos meetup.com directamente. Tenemos un channel de slack para hablar de todo un poco. La mayoría de los miembros se unieron son creando la comunidad en meetup. Gracias a este sitio pudimos contar con la presencia de algunos oradores extranjeros que estaban de visita en Argentina. Cuenten conmigo si necesitan algo. Abrazo y espero que se cree esa comunidad muy pronto!

**Comment by molekilla** [comment]
Aquí en Panamá, ng-panama lo hacemos mensual y el core chapter es de máximo seis personas. Pueden coexistir varios ng-panama, etc. La idea es no consumir el tiempo de la gente pero si vengan energizados con preguntas y novedades. Tenemos un github repo con los estatutos y reusamos otras comunidades en Facebook como Trisfera que es generalista para announcements

**Comment by ricardoerl** [comment]
@mgtitimoli slack suena bien, vamos a probar para comunicarnos mas rápido.

@julianduque gracias Julian, es bueno saberlo.

@eafelix @nisnardi  estuve revisando meetup y veo que casi todas las comunidades grandes lo usan, me parece excelente. Solo tengo una duda, ¿hay algún costo por montar un evento?

@molekilla ¿cuanto mas o menos dura un ng-panama?

**Comment by molekilla** [comment]
@ricardoerl Tratamos sea 1 h, la 1ra el kickoff en Abril fue 2h a 2 1/2 h. Hubo si muchas cosas que entre 6 veteranos no sabiamos, unos usan kendo, ionic, etc. Quedo bien y puede ser sostenible que mi experiencia con mega comunidades (20+)

**Comment by eafelix** [comment]
Pueden hacer algo como la meetup que organiza @nisnardi y sus amigos. http://www.meetup.com/Meetup-js/ 
Es una meetup donde se ve todo lo que respecta a JS, sea node o frontend, es muy lindo formato.

**Comment by molekilla** [comment]
+1 empieza general, si crece, crea especificas (ng-countryName,
react-countryName, etc)

**Comment by eafelix** [comment]
Ya pensaron en el hosting del evento? tendrian que ir buscando sponsors

**Comment by ro-puente** [comment]
@eafelix pues el lugar ya lo tenemos y no va a costar nada. Proyector, pantallas e internet van incluído.

**Comment by bevacqua** [comment]
Les pido si pueden mover esta discusión a wg-comunidades así podemos limpiar un poco la organización
